### ISSUE TITLE
add template support to the HtmlRenderer

### ISSUE THREAD

**Issue by dabutvin** [amzn/tiny-attribution-generator#6]
right now the renderer only operates on `LicenseBucket[]` and the HTML renderer doesn't allow customizing the look and feel at all.

This issue is to extend the renderer with an optional template.

Was thinking of using something like: https://lodash.com/docs/4.17.10#template

**Comment by dabutvin** [comment]
I was thinking to do a single template for the whole document. What other files would be in the folder?

The template string would look something like

```
<!doctype html>
<html>
<head>
    .
    .
    .
</head>
<body>
<h1>My custom heading</h1>
.
.
.
 <ul>
      <% _.forEach(bucket.packages, function(pkg) { %>
          <li>
               <%- pkg.name %> <%- pkg.version %>
          </li>
      <% }) %>
</ul>
.
.
.
</body>
</html>
```


Would you rather use `handlebars` than `lodash`?

**Comment by jpeddicord** [comment]
Eh, I'm just more familiar with Handlebars being purely a template language instead of JavaScript. But I wouldn't complain if you wanted to try this out with lodash instead; there's some simplicity in that. :)

My thinking around templates actually goes a little beyond HTML: One template could be used for an HTML doc, but there's also a possibility for adding, say, an Android view generator (which would probably involve multiple output files). That's way-far-off brainstorming though; assuming a single file output is totally OK right now.

**Comment by dabutvin** [comment]
great. let's go with [handlebars](https://www.npmjs.com/package/handlebars)
